/// <reference types="node" />
import { RestEndpointMethodTypes, Octokit } from "@octokit/rest";
export declare type FileMode = "100644" | "100755" | "040000" | "160000" | "120000";
export declare type FileType = "blob" | "tree" | "commit";
export declare type TreeFile = {
    path: string;
    content: string | Buffer;
};
export interface BaseOptions {
    owner: string;
    repo: string;
}
export declare type GetReferenceCommitOptions = RestEndpointMethodTypes["git"]["getRef"]["parameters"];
export declare const getReferenceCommit: (github: Octokit, options: GetReferenceCommitOptions) => Promise<{
    ref: string;
    node_id: string;
    url: string;
    object: {
        type: string;
        sha: string;
        url: string;
    };
} | undefined>;
export declare type CreateTreeOptions = {
    files: TreeFile[];
    referenceCommitSha?: string;
} & BaseOptions;
export declare const createTree: (github: Octokit, options: CreateTreeOptions) => Promise<string | undefined>;
export declare type CreateCommitOptions = BaseOptions & {
    commitMessage: string;
    tree: string;
    referenceCommitSha?: string;
};
export declare const createCommit: (github: Octokit, options: CreateCommitOptions) => Promise<{
    newCommitSha: string;
}>;
export declare type UpdateReferenceOptions = BaseOptions & {
    ref: string;
    sha: string;
    force?: boolean;
};
export declare const updateReference: (github: Octokit, options: UpdateReferenceOptions) => Promise<{
    ref: string;
    node_id: string;
    url: string;
    object: {
        type: string;
        sha: string;
        url: string;
    };
}>;
export declare type CreateRepositoryOptions = {
    name: string;
};
export declare const createRepository: (github: Octokit, options: CreateRepositoryOptions) => Promise<import("@octokit/types").OctokitResponse<{
    id: number;
    node_id: string;
    name: string;
    full_name: string;
    license: {
        key: string;
        name: string;
        url: string | null;
        spdx_id: string | null;
        node_id: string;
        html_url?: string | undefined;
    } | null;
    organization?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
    } | null | undefined;
    forks: number;
    permissions?: {
        admin: boolean;
        pull: boolean;
        triage?: boolean | undefined;
        push: boolean;
        maintain?: boolean | undefined;
    } | undefined;
    owner: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
    };
    private: boolean;
    html_url: string;
    description: string | null;
    fork: boolean;
    url: string;
    archive_url: string;
    assignees_url: string;
    blobs_url: string;
    branches_url: string;
    collaborators_url: string;
    comments_url: string;
    commits_url: string;
    compare_url: string;
    contents_url: string;
    contributors_url: string;
    deployments_url: string;
    downloads_url: string;
    events_url: string;
    forks_url: string;
    git_commits_url: string;
    git_refs_url: string;
    git_tags_url: string;
    git_url: string;
    issue_comment_url: string;
    issue_events_url: string;
    issues_url: string;
    keys_url: string;
    labels_url: string;
    languages_url: string;
    merges_url: string;
    milestones_url: string;
    notifications_url: string;
    pulls_url: string;
    releases_url: string;
    ssh_url: string;
    stargazers_url: string;
    statuses_url: string;
    subscribers_url: string;
    subscription_url: string;
    tags_url: string;
    teams_url: string;
    trees_url: string;
    clone_url: string;
    mirror_url: string | null;
    hooks_url: string;
    svn_url: string;
    homepage: string | null;
    language: string | null;
    forks_count: number;
    stargazers_count: number;
    watchers_count: number;
    size: number;
    default_branch: string;
    open_issues_count: number;
    is_template?: boolean | undefined;
    topics?: string[] | undefined;
    has_issues: boolean;
    has_projects: boolean;
    has_wiki: boolean;
    has_pages: boolean;
    has_downloads: boolean;
    archived: boolean;
    disabled: boolean;
    visibility?: string | undefined;
    pushed_at: string | null;
    created_at: string | null;
    updated_at: string | null;
    allow_rebase_merge?: boolean | undefined;
    template_repository?: {
        id?: number | undefined;
        node_id?: string | undefined;
        name?: string | undefined;
        full_name?: string | undefined;
        owner?: {
            login?: string | undefined;
            id?: number | undefined;
            node_id?: string | undefined;
            avatar_url?: string | undefined;
            gravatar_id?: string | undefined;
            url?: string | undefined;
            html_url?: string | undefined;
            followers_url?: string | undefined;
            following_url?: string | undefined;
            gists_url?: string | undefined;
            starred_url?: string | undefined;
            subscriptions_url?: string | undefined;
            organizations_url?: string | undefined;
            repos_url?: string | undefined;
            events_url?: string | undefined;
            received_events_url?: string | undefined;
            type?: string | undefined;
            site_admin?: boolean | undefined;
        } | undefined;
        private?: boolean | undefined;
        html_url?: string | undefined;
        description?: string | undefined;
        fork?: boolean | undefined;
        url?: string | undefined;
        archive_url?: string | undefined;
        assignees_url?: string | undefined;
        blobs_url?: string | undefined;
        branches_url?: string | undefined;
        collaborators_url?: string | undefined;
        comments_url?: string | undefined;
        commits_url?: string | undefined;
        compare_url?: string | undefined;
        contents_url?: string | undefined;
        contributors_url?: string | undefined;
        deployments_url?: string | undefined;
        downloads_url?: string | undefined;
        events_url?: string | undefined;
        forks_url?: string | undefined;
        git_commits_url?: string | undefined;
        git_refs_url?: string | undefined;
        git_tags_url?: string | undefined;
        git_url?: string | undefined;
        issue_comment_url?: string | undefined;
        issue_events_url?: string | undefined;
        issues_url?: string | undefined;
        keys_url?: string | undefined;
        labels_url?: string | undefined;
        languages_url?: string | undefined;
        merges_url?: string | undefined;
        milestones_url?: string | undefined;
        notifications_url?: string | undefined;
        pulls_url?: string | undefined;
        releases_url?: string | undefined;
        ssh_url?: string | undefined;
        stargazers_url?: string | undefined;
        statuses_url?: string | undefined;
        subscribers_url?: string | undefined;
        subscription_url?: string | undefined;
        tags_url?: string | undefined;
        teams_url?: string | undefined;
        trees_url?: string | undefined;
        clone_url?: string | undefined;
        mirror_url?: string | undefined;
        hooks_url?: string | undefined;
        svn_url?: string | undefined;
        homepage?: string | undefined;
        language?: string | undefined;
        forks_count?: number | undefined;
        stargazers_count?: number | undefined;
        watchers_count?: number | undefined;
        size?: number | undefined;
        default_branch?: string | undefined;
        open_issues_count?: number | undefined;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues?: boolean | undefined;
        has_projects?: boolean | undefined;
        has_wiki?: boolean | undefined;
        has_pages?: boolean | undefined;
        has_downloads?: boolean | undefined;
        archived?: boolean | undefined;
        disabled?: boolean | undefined;
        visibility?: string | undefined;
        pushed_at?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
        permissions?: {
            admin?: boolean | undefined;
            maintain?: boolean | undefined;
            push?: boolean | undefined;
            triage?: boolean | undefined;
            pull?: boolean | undefined;
        } | undefined;
        allow_rebase_merge?: boolean | undefined;
        temp_clone_token?: string | undefined;
        allow_squash_merge?: boolean | undefined;
        allow_auto_merge?: boolean | undefined;
        delete_branch_on_merge?: boolean | undefined;
        allow_merge_commit?: boolean | undefined;
        subscribers_count?: number | undefined;
        network_count?: number | undefined;
    } | null | undefined;
    temp_clone_token?: string | undefined;
    allow_squash_merge?: boolean | undefined;
    allow_auto_merge?: boolean | undefined;
    delete_branch_on_merge?: boolean | undefined;
    allow_merge_commit?: boolean | undefined;
    allow_forking?: boolean | undefined;
    subscribers_count?: number | undefined;
    network_count?: number | undefined;
    open_issues: number;
    watchers: number;
    master_branch?: string | undefined;
    starred_at?: string | undefined;
}, 201>>;
export declare type CreateRepositoryFromTemplateOptions = {
    templateOwner: string;
    templateRepo: string;
} & CreateRepositoryOptions;
export declare const createRepositoryFromTemplate: (github: Octokit, options: CreateRepositoryFromTemplateOptions) => Promise<import("@octokit/types").OctokitResponse<{
    id: number;
    node_id: string;
    name: string;
    full_name: string;
    license: {
        key: string;
        name: string;
        url: string | null;
        spdx_id: string | null;
        node_id: string;
        html_url?: string | undefined;
    } | null;
    organization?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
    } | null | undefined;
    forks: number;
    permissions?: {
        admin: boolean;
        pull: boolean;
        triage?: boolean | undefined;
        push: boolean;
        maintain?: boolean | undefined;
    } | undefined;
    owner: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
    };
    private: boolean;
    html_url: string;
    description: string | null;
    fork: boolean;
    url: string;
    archive_url: string;
    assignees_url: string;
    blobs_url: string;
    branches_url: string;
    collaborators_url: string;
    comments_url: string;
    commits_url: string;
    compare_url: string;
    contents_url: string;
    contributors_url: string;
    deployments_url: string;
    downloads_url: string;
    events_url: string;
    forks_url: string;
    git_commits_url: string;
    git_refs_url: string;
    git_tags_url: string;
    git_url: string;
    issue_comment_url: string;
    issue_events_url: string;
    issues_url: string;
    keys_url: string;
    labels_url: string;
    languages_url: string;
    merges_url: string;
    milestones_url: string;
    notifications_url: string;
    pulls_url: string;
    releases_url: string;
    ssh_url: string;
    stargazers_url: string;
    statuses_url: string;
    subscribers_url: string;
    subscription_url: string;
    tags_url: string;
    teams_url: string;
    trees_url: string;
    clone_url: string;
    mirror_url: string | null;
    hooks_url: string;
    svn_url: string;
    homepage: string | null;
    language: string | null;
    forks_count: number;
    stargazers_count: number;
    watchers_count: number;
    size: number;
    default_branch: string;
    open_issues_count: number;
    is_template?: boolean | undefined;
    topics?: string[] | undefined;
    has_issues: boolean;
    has_projects: boolean;
    has_wiki: boolean;
    has_pages: boolean;
    has_downloads: boolean;
    archived: boolean;
    disabled: boolean;
    visibility?: string | undefined;
    pushed_at: string | null;
    created_at: string | null;
    updated_at: string | null;
    allow_rebase_merge?: boolean | undefined;
    template_repository?: {
        id?: number | undefined;
        node_id?: string | undefined;
        name?: string | undefined;
        full_name?: string | undefined;
        owner?: {
            login?: string | undefined;
            id?: number | undefined;
            node_id?: string | undefined;
            avatar_url?: string | undefined;
            gravatar_id?: string | undefined;
            url?: string | undefined;
            html_url?: string | undefined;
            followers_url?: string | undefined;
            following_url?: string | undefined;
            gists_url?: string | undefined;
            starred_url?: string | undefined;
            subscriptions_url?: string | undefined;
            organizations_url?: string | undefined;
            repos_url?: string | undefined;
            events_url?: string | undefined;
            received_events_url?: string | undefined;
            type?: string | undefined;
            site_admin?: boolean | undefined;
        } | undefined;
        private?: boolean | undefined;
        html_url?: string | undefined;
        description?: string | undefined;
        fork?: boolean | undefined;
        url?: string | undefined;
        archive_url?: string | undefined;
        assignees_url?: string | undefined;
        blobs_url?: string | undefined;
        branches_url?: string | undefined;
        collaborators_url?: string | undefined;
        comments_url?: string | undefined;
        commits_url?: string | undefined;
        compare_url?: string | undefined;
        contents_url?: string | undefined;
        contributors_url?: string | undefined;
        deployments_url?: string | undefined;
        downloads_url?: string | undefined;
        events_url?: string | undefined;
        forks_url?: string | undefined;
        git_commits_url?: string | undefined;
        git_refs_url?: string | undefined;
        git_tags_url?: string | undefined;
        git_url?: string | undefined;
        issue_comment_url?: string | undefined;
        issue_events_url?: string | undefined;
        issues_url?: string | undefined;
        keys_url?: string | undefined;
        labels_url?: string | undefined;
        languages_url?: string | undefined;
        merges_url?: string | undefined;
        milestones_url?: string | undefined;
        notifications_url?: string | undefined;
        pulls_url?: string | undefined;
        releases_url?: string | undefined;
        ssh_url?: string | undefined;
        stargazers_url?: string | undefined;
        statuses_url?: string | undefined;
        subscribers_url?: string | undefined;
        subscription_url?: string | undefined;
        tags_url?: string | undefined;
        teams_url?: string | undefined;
        trees_url?: string | undefined;
        clone_url?: string | undefined;
        mirror_url?: string | undefined;
        hooks_url?: string | undefined;
        svn_url?: string | undefined;
        homepage?: string | undefined;
        language?: string | undefined;
        forks_count?: number | undefined;
        stargazers_count?: number | undefined;
        watchers_count?: number | undefined;
        size?: number | undefined;
        default_branch?: string | undefined;
        open_issues_count?: number | undefined;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues?: boolean | undefined;
        has_projects?: boolean | undefined;
        has_wiki?: boolean | undefined;
        has_pages?: boolean | undefined;
        has_downloads?: boolean | undefined;
        archived?: boolean | undefined;
        disabled?: boolean | undefined;
        visibility?: string | undefined;
        pushed_at?: string | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
        permissions?: {
            admin?: boolean | undefined;
            maintain?: boolean | undefined;
            push?: boolean | undefined;
            triage?: boolean | undefined;
            pull?: boolean | undefined;
        } | undefined;
        allow_rebase_merge?: boolean | undefined;
        temp_clone_token?: string | undefined;
        allow_squash_merge?: boolean | undefined;
        allow_auto_merge?: boolean | undefined;
        delete_branch_on_merge?: boolean | undefined;
        allow_merge_commit?: boolean | undefined;
        subscribers_count?: number | undefined;
        network_count?: number | undefined;
    } | null | undefined;
    temp_clone_token?: string | undefined;
    allow_squash_merge?: boolean | undefined;
    allow_auto_merge?: boolean | undefined;
    delete_branch_on_merge?: boolean | undefined;
    allow_merge_commit?: boolean | undefined;
    allow_forking?: boolean | undefined;
    subscribers_count?: number | undefined;
    network_count?: number | undefined;
    open_issues: number;
    watchers: number;
    master_branch?: string | undefined;
    starred_at?: string | undefined;
}, 201>>;
export declare type GetBranchesOptions = BaseOptions & {};
export declare const getBranches: (github: Octokit, options: GetBranchesOptions) => Promise<{
    name: string;
    commit: {
        sha: string;
        url: string;
    };
    protected: boolean;
    protection?: {
        url?: string | undefined;
        enabled?: boolean | undefined;
        required_status_checks?: {
            url?: string | undefined;
            enforcement_level?: string | undefined;
            contexts: string[];
            contexts_url?: string | undefined;
            strict?: boolean | undefined;
        } | undefined;
        enforce_admins?: {
            url: string;
            enabled: boolean;
        } | undefined;
        required_pull_request_reviews?: {
            url?: string | undefined;
            dismissal_restrictions?: {
                users?: {
                    name?: string | null | undefined;
                    email?: string | null | undefined;
                    login: string;
                    id: number;
                    node_id: string;
                    avatar_url: string;
                    gravatar_id: string | null;
                    url: string;
                    html_url: string;
                    followers_url: string;
                    following_url: string;
                    gists_url: string;
                    starred_url: string;
                    subscriptions_url: string;
                    organizations_url: string;
                    repos_url: string;
                    events_url: string;
                    received_events_url: string;
                    type: string;
                    site_admin: boolean;
                    starred_at?: string | undefined;
                }[] | undefined;
                teams?: {
                    id: number;
                    node_id: string;
                    name: string;
                    slug: string;
                    description: string | null;
                    privacy?: string | undefined;
                    permission: string;
                    permissions?: {
                        pull: boolean;
                        triage: boolean;
                        push: boolean;
                        maintain: boolean;
                        admin: boolean;
                    } | undefined;
                    url: string;
                    html_url: string;
                    members_url: string;
                    repositories_url: string;
                    parent: {
                        id: number;
                        node_id: string;
                        url: string;
                        members_url: string;
                        name: string;
                        description: string | null;
                        permission: string;
                        privacy?: string | undefined;
                        html_url: string;
                        repositories_url: string;
                        slug: string;
                        ldap_dn?: string | undefined;
                    } | null;
                }[] | undefined;
                url?: string | undefined;
                users_url?: string | undefined;
                teams_url?: string | undefined;
            } | undefined;
            dismiss_stale_reviews: boolean;
            require_code_owner_reviews: boolean;
            required_approving_review_count?: number | undefined;
        } | undefined;
        restrictions?: {
            url: string;
            users_url: string;
            teams_url: string;
            apps_url: string;
            users: {
                login?: string | undefined;
                id?: number | undefined;
                node_id?: string | undefined;
                avatar_url?: string | undefined;
                gravatar_id?: string | undefined;
                url?: string | undefined;
                html_url?: string | undefined;
                followers_url?: string | undefined;
                following_url?: string | undefined;
                gists_url?: string | undefined;
                starred_url?: string | undefined;
                subscriptions_url?: string | undefined;
                organizations_url?: string | undefined;
                repos_url?: string | undefined;
                events_url?: string | undefined;
                received_events_url?: string | undefined;
                type?: string | undefined;
                site_admin?: boolean | undefined;
            }[];
            teams: {
                id?: number | undefined;
                node_id?: string | undefined;
                url?: string | undefined;
                html_url?: string | undefined;
                name?: string | undefined;
                slug?: string | undefined;
                description?: string | null | undefined;
                privacy?: string | undefined;
                permission?: string | undefined;
                members_url?: string | undefined;
                repositories_url?: string | undefined;
                parent?: string | null | undefined;
            }[];
            apps: {
                id?: number | undefined;
                slug?: string | undefined;
                node_id?: string | undefined;
                owner?: {
                    login?: string | undefined;
                    id?: number | undefined;
                    node_id?: string | undefined;
                    url?: string | undefined;
                    repos_url?: string | undefined;
                    events_url?: string | undefined;
                    hooks_url?: string | undefined;
                    issues_url?: string | undefined;
                    members_url?: string | undefined;
                    public_members_url?: string | undefined;
                    avatar_url?: string | undefined;
                    description?: string | undefined;
                    gravatar_id?: string | undefined;
                    html_url?: string | undefined;
                    followers_url?: string | undefined;
                    following_url?: string | undefined;
                    gists_url?: string | undefined;
                    starred_url?: string | undefined;
                    subscriptions_url?: string | undefined;
                    organizations_url?: string | undefined;
                    received_events_url?: string | undefined;
                    type?: string | undefined;
                    site_admin?: boolean | undefined;
                } | undefined;
                name?: string | undefined;
                description?: string | undefined;
                external_url?: string | undefined;
                html_url?: string | undefined;
                created_at?: string | undefined;
                updated_at?: string | undefined;
                permissions?: {
                    metadata?: string | undefined;
                    contents?: string | undefined;
                    issues?: string | undefined;
                    single_file?: string | undefined;
                } | undefined;
                events?: string[] | undefined;
            }[];
        } | undefined;
        required_linear_history?: {
            enabled?: boolean | undefined;
        } | undefined;
        allow_force_pushes?: {
            enabled?: boolean | undefined;
        } | undefined;
        allow_deletions?: {
            enabled?: boolean | undefined;
        } | undefined;
        required_conversation_resolution?: {
            enabled?: boolean | undefined;
        } | undefined;
        name?: string | undefined;
        protection_url?: string | undefined;
        required_signatures?: {
            url: string;
            enabled: boolean;
        } | undefined;
    } | undefined;
    protection_url?: string | undefined;
}[]>;
